apiVersion: apps/v1
kind: Deployment
metadata:
  name: ajay-2025-deploy
  labels:
    app: ajay-2025-deploy-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ajay-2025-app
  template:
    metadata:
      labels:
        app: ajay-2025-app
    spec:
      containers:
      - name: ajay-2025-container
        image: ajaynew2025/webappimage:v1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ajay-2025-np-service
  labels:
    app: ajay-2025-app
spec:
  selector:
    app: ajay-2025-deploy-lbl

  type: NodePort
  ports:
  - nodePort: 31028
    port: 8080
    targetPort: 8080
